version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: superset-redis
    ports:
      - "6380:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:13
    container_name: superset-db
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    ports:
      - "5436:5432"
    volumes:
      - superset-db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "superset"]
      interval: 10s
      timeout: 5s
      retries: 5

  superset:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-superset:latest #apache/superset:latest
    container_name: superset-app
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=your-secret-key-here
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
      - POSTGRES_DB=superset
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      #- PIP_ADDITIONAL_REQUIREMENTS=clickhouse-sqlalchemy==0.2.4 clickhouse-driver==0.2.6 sqlalchemy-clickhouse
    volumes:
      - superset-config:/app/superset_home
    depends_on:
      - db
      - redis
    restart: unless-stopped
    command: >
          bash -c "superset db upgrade &&
           superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin &&
           superset init &&
           superset run -h 0.0.0.0 -p 8088"
    networks:
      - airflow-spark-net


volumes:
  superset-db:
  superset-config:

networks:
  airflow-spark-net:
    external: true
